### ISSUE TITLE
git color causes errors

### ISSUE THREAD

**Issue by bbergstrom** [sportngin/octopolo#109]
Octopolo should give better error messages or handle colored git responses better.

Here is an example of new-branch failing, I'm sure other commands fail as well when git color is set to always in the users git config.
```
git branch --no-track tacos origin/master
git checkout tacos
error: Failed to check out 'tacos'
/usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/octopolo-1.4.0/lib/octopolo/git.rb:87:in `check_out': Failed to check out 'tacos' (Octopolo::Git::CheckoutFailed)
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/octopolo-1.4.0/lib/octopolo/git.rb:102:in `new_branch'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/octopolo-1.4.0/lib/octopolo/scripts/new_branch.rb:27:in `execute'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/octopolo-1.4.0/lib/octopolo/scripts/new_branch.rb:15:in `execute'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/octopolo-1.4.0/lib/octopolo/commands/new_branch.rb:7:in `block (2 levels) in <top (required)>'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `call'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `execute'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/app_support.rb:296:in `block in call_command'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call_command'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/gli-2.14.0/lib/gli/app_support.rb:83:in `run'
    from /usr/local/Cellar/gem-sportngin-octopolo-workflow/1.5.0/gems/sportngin-octopolo-workflow-1.5.0/bin/op:50:in `<top (required)>'
    from /usr/local/bin/op:5:in `load'
    from /usr/local/bin/op:5:in `<main>'
```

**Comment by nicksieger** [comment]
Ouch. Seems like the only option is to supply `--color=never` on the command-line?
